/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bluesealbank;

import bluesealbank.config.Trail;
import java.sql.*;
import bluesealbank.config.config;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Shadrack
 */
public class frmDeposit extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pstmt;
    
    private int bk_id;
    private int depositAmount = 0;
    
    
    Trail trail;
    
    /**
     * Creates new form FRMdEPOSIT
     */
    public frmDeposit() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        ButtonGroup bgp = new ButtonGroup();
        bgp.add(rb50);
        bgp.add(rb100);
        bgp.add(rb500);
        bgp.add(rb1000);
        bgp.add(rbOwn);

    }
    
    
    
   
    private void DepositMoney() {
       
        // initialize object
        trail = new Trail();
        
        // first check wether the user has selected any of the radio button or options
      
        if (rb50.isSelected()) {
            depositAmount = 50;
        }
        
        else if(rb100.isSelected()) {
            depositAmount = 100;
        }
        
        else if (rb500.isSelected()) {
            depositAmount = 500;
        }
        
        else if (rb1000.isSelected()) {
            depositAmount = 1000;
        }
        else if(rbOwn.isSelected()) {
            depositAmount = Integer.parseInt(txtOwnAmount.getText());
        }
        
        // now lets connect to the data base and store / deposit the money to the bank
        if (depositAmount > 0) {
            try {
            conn = DriverManager.getConnection(config.url, config.user, config.pass);
           
  
            String depositQuery = "UPDATE userdetails SET Balance = Balance + ? WHERE ID_Number=?";
            

            PreparedStatement pstmt = conn.prepareStatement(depositQuery);
            pstmt.setInt(1, depositAmount);
            pstmt.setLong(2, UserModel.getIdNumber());
            int rowsAffected = pstmt.executeUpdate();
            
            trail.setDepartment("Expenses");
            trail.setValue(depositAmount);
            
//            trail.storeToArray(trail.getDepartment(), trail.getValue());
           
            System.out.println("Successfully deposited the cash." + rowsAffected);
            JOptionPane.showMessageDialog(null, "Successfully Deposited R" + depositAmount + " to " + UserModel.getPreferredAccountType() + " Account", "Deposit", JOptionPane.INFORMATION_MESSAGE);
            dashBoard dash = new dashBoard();
            dash.show();
            this.hide();
        }
        
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "Failed to insert data, try again later." + ex.getMessage());
        }
        }
        else {
            JOptionPane.showMessageDialog(null, "Please Enter Or Select An Amount Greater Then R0!, Please Try Again.", "Cash Amount Insufficient", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        // lests get the user id when a user logs in at the log-in tab
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDeposit = new javax.swing.JButton();
        rb50 = new javax.swing.JRadioButton();
        rb100 = new javax.swing.JRadioButton();
        rb1000 = new javax.swing.JRadioButton();
        rb500 = new javax.swing.JRadioButton();
        txtOwnAmount = new javax.swing.JTextField();
        rbOwn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BlueSealBank");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        rb50.setBackground(new java.awt.Color(255, 255, 255));
        rb50.setText("50");

        rb100.setBackground(new java.awt.Color(255, 255, 255));
        rb100.setText("100");

        rb1000.setBackground(new java.awt.Color(255, 255, 255));
        rb1000.setText("1 000");

        rb500.setBackground(new java.awt.Color(255, 255, 255));
        rb500.setText("500");

        rbOwn.setBackground(new java.awt.Color(255, 255, 255));
        rbOwn.setText("Own Amount");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deposit");

        lblBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setText("<");
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(rbOwn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOwnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb1000)
                                    .addComponent(rb50))
                                .addGap(135, 135, 135)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb100)
                                    .addComponent(rb500)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb100)
                    .addComponent(rb50))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1000)
                    .addComponent(rb500))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOwnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbOwn))
                .addGap(39, 39, 39)
                .addComponent(btnDeposit)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        DepositMoney();
    }//GEN-LAST:event_btnDepositActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        // Go back to previous tab
        
        dashBoard dash = new dashBoard();
        dash.show();
        this.hide();
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        // TODO add your handling code here:
        lblBack.setOpaque(true);
        lblBack.setBackground(Color.decode("#c7c7c7"));
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseExited
        // TODO add your handling code here:
        
        lblBack.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblBackMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        
        // Boolean Expression
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to close the application?", "Close Operation", JOptionPane.OK_CANCEL_OPTION);
        
        /**
         * We do a Boolean expression where we get the int value 1(True) or 0(False) 
         * then we do an if statement, if the user Chooses OK then close the Application
         * Otherwise Do Nothing
         */
        if(choice == JOptionPane.OK_OPTION) {
            // Close the Application
            JOptionPane.showMessageDialog(this, "Bye Bye!");
            System.exit(0);
            
        }
        else {
            // Do Nothing
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDeposit().setVisible(true);
            }
        });
    }
    
    
   
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JRadioButton rb100;
    private javax.swing.JRadioButton rb1000;
    private javax.swing.JRadioButton rb50;
    private javax.swing.JRadioButton rb500;
    private javax.swing.JRadioButton rbOwn;
    private javax.swing.JTextField txtOwnAmount;
    // End of variables declaration//GEN-END:variables
}
