/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;
import bluesealbank.ConnectDatabase;
import bluesealbank.DBPrompt;
import bluesealbank.UserModel;
import bluesealbank.config.config;
import bluesealbank.dashBoard;
import com.sun.jna.Platform;
import java.sql.*;
import java.util.concurrent.CompletableFuture;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author Shadrack
 */
public class Withdraw extends javax.swing.JPanel {

    /**
     * Creates new form Withdraw
     */
    
    ConnectDatabase connWithdraw = new ConnectDatabase();
    public double deductAmount;
    
    // Mysql Required Object
    Connection conn;
    PreparedStatement pstmt;
    ResultSet rs;
    
    
    
    
    
    public Withdraw() {
        initComponents();
        
    }
    
    public void deductMoneyFromAccount() {
        
        double Amount = Double.parseDouble(txtAmount.getText());
        
        try {
            conn = DriverManager.getConnection(config.url, config.user, config.pass);
            
            String sql = "Update userdetails set Balance = ? where ID_Number=?";
            
            double balance = UserModel.getBalance();
            
            if(balance < Amount || Amount < 0) {
               JOptionPane.showMessageDialog(null, "Insufficient Funds!");
            }
            else{
              deductAmount = balance - Amount;
              
           // Save balance to the UserModel Object balance variable
           UserModel.setBalance(deductAmount);
            
            pstmt = conn.prepareStatement(sql);
            pstmt.setDouble(1, deductAmount);
            pstmt.setLong(2, UserModel.getIdNumber());
            int rowsAffected = pstmt.executeUpdate();
              if(rowsAffected > 0) {
                System.out.println("Successfully Withdrew Money");
                JOptionPane.showMessageDialog(null, "Successfully Withdrew R " + Amount + " from Account");
                
            }
            else {
                  System.out.println("Failed to Withdraw Money");
                  JOptionPane.showMessageDialog(null, "Failed to Withdraw Money");
              }
        }
            }

            
            
        catch(Exception ex) {
            System.out.println("The Process of withdrawal Failed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnwithdraw = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Withdraw");

        jLabel2.setText("Amount");

        btnwithdraw.setText("Withdraw");
        btnwithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwithdrawActionPerformed(evt);
            }
        });

        jLabel3.setText("<html>\n<style>\nbody{\nfont-family: \"Arial\", sans-serif;\nfont-size: 1em;\n}\n\nh1 {\nfont-size: 2em;\ntext-transform: uppercase;\njustify-content: center;\npadding: 10px;\n}\n\np {\nmargin: 10px;\n}\n\nspan{\ncolor: #138808;\n}\n</style>\n<body>\n<h1>How to withdraw Money</h1>\n<p>To <span>withdraw money</span> just enter your desired amount to widraw in the <sup>textbox</sup> below. Once you enter your desired amount just press the widrawal button at the bottom.</p>\n\n</body>\n</html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(btnwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnwithdraw)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnwithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwithdrawActionPerformed

        deductMoneyFromAccount();
    }//GEN-LAST:event_btnwithdrawActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnwithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
